name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: dotnet-sonarscanner
      uses: Secbyte/dotnet-sonarscanner@v2.2
      with:
        # Command to invoke build
        buildCommand: dotnet build --configuration Release --no-restore
        # Command to invoke tests
        testCommand: dotnet test --no-restore --verbosity normal
        # Specifies the key of the analyzed project in SonarQube
        projectKey: autowire
        # Specifies the name of the analyzed project in SonarQube
        projectName: autowire
        # The server URL
        sonarHostname: http://localhost:9000
        # Organisation
        sonarOrganisation: default
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
