name: AutoWire

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install dependencies
      uses: docker://mcr.microsoft.com/dotnet/core/sdk:3.1
      with:
        entrypoint: dotnet
        args: restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: TGX.Extensions.DependencyInjection.AutoWire/bin/Release/netstandard2.0
